# Generated by Django 4.0.8 on 2023-03-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAttr',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='blog.article')),
                ('title_length', models.IntegerField(verbose_name='标题的字符个数')),
                ('body_length', models.IntegerField(verbose_name='body的字符个数')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
