FROM python:3
WORKDIR /home
RUN git clone https://github.com/jiangyuxustore/dxflearn.git
ENV basepath /home/dxflearn
WORKDIR $basepath
RUN git config --global url.https://github.com/.insteadOf git://github.com/
RUN pip install -i https://pypi.douban.com/simple flask flask_restful
RUN chmod 777 startflask.sh
RUN ls
RUN pwd
EXPOSE 5000
ENTRYPOINT ["sh /home/dxflearn/startflask.sh"]
CMD ["/bin/bash"]
