# Generated by Django 4.0.8 on 2023-03-05 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='主键订单号')),
                ('order_amount', models.FloatField(verbose_name='订单金额')),
                ('order_status', models.IntegerField(default=1, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('order_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='下单的用户名')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
