# Generated by Django 4.0.8 on 2023-03-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_order_order_id_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键订单号'),
        ),
    ]
